server:
  port: 8083

spring:
  kafka:
    topic:
      name: order_topics
    consumer:
      bootstrap-servers: localhost:9092
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  config:
    import: env.properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_EMAIL_USER}
    password: ${SPRING_EMAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
